[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "build"
command = "sh"
command_arguments = ["-c", "npx --yes tailwindcss -i ./src/styles/tailwind.css -o $TRUNK_STAGING_DIR/tailwind.css"]

[[proxy]]
rewrite = "/api/v1/"
backend = "http://localhost:9000/"
